---
- hosts: all
  become: true
  tasks:
    - name: Install the apache2 package
      package:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: add php support for apache
      package:
        name: libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
