---
- hosts: all
  become: true
  tasks:
    - name: Update repository index, remove the apache2 and php packages
      apt:
        update_cache: yes
        name:
          - apache2
          - libapache2-mod-php
        state: absent
