---
- hosts: all
  become: true
  pre_tasks:
    - name: install updates for CentOS
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: install updates for Ubuntu
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:
    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.13.0/terraform_0.13.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

- hosts: web_servers
  become: true
  tasks:
    - name: Install apache servers
      tags: apache,apache2,ubuntu
      package:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: add php support for apache servers
      tags: apache,apache2,ubuntu,php
      package:
        name: libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: copy
      tags: apache,apache2
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: db_servers
  become: true
  tasks:
    - name: Install CentOS servers
      tags: apache,centos,httpd
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

- hosts: file_servers
  tags: samba
  become: true
  tasks:
    - name: Install samba
      package:
        name: samba
        state: latest
